### ISSUE TITLE
起動時、稀にClassCastExceptionでクラッシュする

### ISSUE THREAD

**Issue by Siro256** [Kotatsu-RTM/fixRTM#9]
<details>
  <summary>Stacktrace</summary>

```
com.anatawa12.fixRtm.rtm.modelpack.init.ModelConstructingException: constructing resource: rail_sh-1_kb-65_r65_1435_used (source file: H:\Minecraft\1.12.2-waya\mods\[RTM]Project_KC-160[rail][1435][advanced][1.2.2].zip\assets\minecraft\jsons\rail\ModelRail_rail_sh-1_kb-65_r65_1435_used.json)
	at com.anatawa12.fixRtm.rtm.modelpack.init.ExModelPackConstructThread.construct(ExModelPackConstructThread.kt:134)
	at com.anatawa12.fixRtm.rtm.modelpack.init.ExModelPackConstructThread.runThread$lambda$3(ExModelPackConstructThread.kt:99)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.ClassCastException: java.lang.invoke.LambdaForm cannot be cast to [Ljava.lang.invoke.LambdaFormEditor$Transform;
	at java.lang.invoke.LambdaFormEditor.getInCache(LambdaFormEditor.java:275)
	at java.lang.invoke.LambdaFormEditor.filterArgumentForm(LambdaFormEditor.java:635)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:230)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:194)
	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:380)
	at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:776)
	at java.lang.invoke.MethodHandle.asType(MethodHandle.java:761)
	at jdk.nashorn.internal.lookup.MethodHandleFactory$StandardMethodHandleFunctionality.asType(MethodHandleFactory.java:419)
	at jdk.nashorn.internal.codegen.ObjectClassGenerator.createSetter(ObjectClassGenerator.java:715)
	at jdk.nashorn.internal.runtime.AccessorProperty.generateSetter(AccessorProperty.java:591)
	at jdk.nashorn.internal.runtime.AccessorProperty.getSetter(AccessorProperty.java:623)
	at jdk.nashorn.internal.runtime.ScriptObject.addSpill(ScriptObject.java:2528)
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGlobalPropertySetter(SetMethodCreator.java:184)
	at jdk.nashorn.internal.runtime.SetMethodCreator.createSetMethod(SetMethodCreator.java:129)
	at jdk.nashorn.internal.runtime.SetMethodCreator.createGuardedInvocation(SetMethodCreator.java:84)
	at jdk.nashorn.internal.runtime.ScriptObject.findSetMethod(ScriptObject.java:2177)
	at jdk.nashorn.internal.objects.Global.findSetMethod(Global.java:2207)
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1823)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$10453$\^eval\_.:program(<eval>:180)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at jp.ngt.ngtlib.io.ScriptUtil.doScript(ScriptUtil.java(modified by fixrtm):60)
	at com.anatawa12.fixRtm.scripting.FIXScriptUtil.getScriptAndDoScript(FIXScriptUtil.kt:34)
	at jp.ngt.rtm.render.RTMRenderers.getRendererWithScript(RTMRenderers.java(modified by fixrtm):14)
	at jp.ngt.rtm.render.ModelObject.getPartsRenderer(ModelObject.java(modified by fixrtm):117)
	at jp.ngt.rtm.render.ModelObject.<init>(ModelObject.java(modified by fixrtm):82)
	at jp.ngt.rtm.modelpack.modelset.ModelSetRail.constructOnClient(ModelSetRail.java:41)
	at com.anatawa12.fixRtm.rtm.modelpack.init.ExModelPackConstructThread.construct(ExModelPackConstructThread.kt:118)
	... 6 more
```

</details>

**Comment by Siro256** [comment]
ExModelPackConstructThreadを削除したのでこの問題は発生しない
